name: deploy-artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    tags:
    - 'v*'
  pull_request:
    branches: [ "master" ]
    tags:
    - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
      - name: Install platformIO libraries
        run: pio lib install
      - name: Build Production Image
        run: pio run -e production
      - name: Archive Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware.bin
          path: .pio/build/production/firmware.bin
      - name: Build Production FS Image
        run: pio run -e production -t buildfs
      - name: Archive Filesystem
        uses: actions/upload-artifact@v3
        with:
          name: littlefs.bin
          path: .pio/build/production/littlefs.bin
